export { default as networkStatusDe } from './i18n/de'
export { default as networkStatusEn } from './i18n/en'
export { useNetworkStatus } from './model/use-network-status'
export { checkHeartbeatConnectivity } from './service/check-heartbeat'
export { default as NetworkStatus } from './ui/NetworkStatus.vue'
