name: Dev Workflow
description: Adaptation or expansion of the development workflow
title: "DEV: "
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be implemented or changed?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is the change necessary?
      placeholder: For example, local testing is currently complex and time-consuming...
    validations:
      required: false

  - type: textarea
    id: current_state
    attributes:
      label: Current State
      description: How does the current workflow look?
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact
      options:
        - label: Influences local development
        - label: Influences CI/CD
        - label: Requires new tools
        - label: Breaking Change

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Links, Screenshots, References etc.
